#!/bin/bash
# CopyFiles - Script to install Samba AD DC and copy configuration files to their proper location.
#		(Fist save originals as *.orig)

# Default UMASK
sed -i "s/^UMASK.*022/UMASK\t\t002/" /etc/login.defs

# Sync time with the AD DC
sed -i -nr '/NTP=/!p;$aNTP=DC1.samdom.example.com' /etc/systemd/timesyncd.conf

# Install Samba and packages needed to integrate into the domain (Done with CopyFiles).
apt install -y samba winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user

# Also install some utility programs:
apt install -y net-tools wsdd $(check-language-support)

# Stop all Samba processes and remove the default smb.conf file:
systemctl stop smbd nmbd winbind
mv /etc/samba/smb.conf /etc/samba/smb.conf.orig

# Copy the Samba configuration file:
cp /root/Kubuntu/config/smb.conf /etc/samba/

# Backup and copy the Kerberos configuration file:
mv /etc/krb5.conf /etc/skrb5.conf.orig
cp /root/Kubuntu/config/krb5.conf /etc/

# sudo for Domain Admins
cp /root/Kubuntu/config/SAMDOM /etc/sudoers.d/

# Static IP for VirtualBox network interface  <-- Disabled
#cp /root/DC1/config/VirtualBox /etc/network/interfaces.d/
