#!/bin/bash
# CopyFiles - Script to install Samba AD DC and copy configuration files to their proper location.
#		(Fist save originals as *.orig)

# Default UMASK
sed -i "s/^UMASK.*022/UMASK\t\t002/" /etc/login.defs

# Sync time with the AD DC
sed -i -nr '/NTP=/!p;$aNTP=DC1.samdom.example.com' /etc/systemd/timesyncd.conf

# Install Samba and packages needed to integrate into the domain (Done with CopyFiles).
apt install -y samba winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user

# Also install some utility programs:
apt install -y net-tools wsdd $(check-language-support)

# Stop all Samba processes and remove the default smb.conf file:
systemctl stop smbd nmbd winbind
mv /etc/samba/smb.conf /etc/samba/smb.conf.orig

# Edit the Samba configuration file:
sed -i '/rfc2307/r /root/DC1/config/smb.insert' /etc/samba/smb.conf

# Use the Samba created Kerberos configuration file for your DC, enable the correct Samba services:
cp /var/lib/samba/private/krb5.conf /etc/
systemctl unmask samba-ad-dc
systemctl start samba-ad-dc
systemctl enable samba-ad-dc

# Copy script to cron.hourly that sets RFC2307 attributes in the SAMBA AD DC
cp /root/DC1/RFC2307 /etc/cron.hourly/
/etc/cron.hourly/RFC2307

# Fix permissions for the domain on sysvol
chown 10500:10512 -R /var/lib/samba/sysvol/samdom.example.com/

# DNS name resolving
sed -i -nr '/dns-nameservers/!p;$a\\tdns-nameservers 10.0.2.5' /etc/network/interfaces

# Chrony Time Service
mv /etc/chrony/chrony.conf /etc/chrony/chrony.conf.orig
cp /root/DC1/config/chrony.conf /etc/chrony/
mkdir /var/lib/samba/ntp_signd
chown root:_chrony /var/lib/samba/ntp_signd/
chmod 750 /var/lib/samba/ntp_signd/

# sudo for Domain Admins
cp /root/DC1/config/SAMDOM /etc/sudoers.d/

# DHCP Service
mv /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server.orig
cp /root/DC1/config/isc-dhcp-server /etc/default/
mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.orig
cp /root/DC1/config/dhcpd.conf /etc/dhcp/

# Static IP for VirtualBox network interface
cp /root/DC1/config/VirtualBox /etc/network/interfaces.d/
