#!/bin/bash
# RFC2307 - Script to set RFC2307 attributes in the SAMBA Active Directory Domain Controller
 
FIRST_ID=10000
CHANGES=0
 
# Find users and computers without a uidNumber and groups without a gidNumber
 
# Add a uidNumber, home directory and shell to user accounts
while read DN; do
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	IDNUMBER=$(($FIRST_ID + $RID))
	if [ -t 1 ]; then printf "Adding uidNumber '$IDNUMBER' to '$DN'\n"; fi
 
	TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
	printf "dn: $DN\n" >$TMP_FILE
	printf "changeType: modify\n" >>$TMP_FILE
	printf "add: uidNumber\n" >>$TMP_FILE
	printf "uidNumber: ${IDNUMBER}\n" >>$TMP_FILE
	printf "add: unixHomeDirectory\n" >>$TMP_FILE
	printf "unixHomeDirectory: /home/%%U\n" >>$TMP_FILE
	printf "add: loginShell\n" >>$TMP_FILE
	if [ $RID -ge 1000 ]
	then
		printf "loginShell: /bin/bash\n" >>$TMP_FILE
	else
# No login for system accounts (RID < 1000)
		printf "loginShell: /usr/sbin/nologin\n" >>$TMP_FILE
	fi
 
	ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
	if [ -t 1 ]; then cat $TMP_FILE; fi
	((CHANGES++))
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=User)(!(ObjectClass=computer))(!(uidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
# Add a uidNumber to computers
while read DN; do
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	if [ $RID -ge 1000 ]
	then
		IDNUMBER=$(($FIRST_ID + $RID))
		if [ -t 1 ]; then printf "Adding uidNumber '$IDNUMBER' to '$DN'\n"; fi
 
		TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
		printf "dn: $DN\n" >$TMP_FILE
		printf "changeType: modify\n" >>$TMP_FILE
		printf "add: uidNumber\n" >>$TMP_FILE
		printf "uidNumber: ${IDNUMBER}\n" >>$TMP_FILE
 
		ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
		if [ -t 1 ]; then cat $TMP_FILE; fi
	        ((CHANGES++))
	else
		if [ -t 1 ]; then printf "Skipping computer '$DN'\n"; fi
	fi
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=User)(ObjectClass=computer)(!(uidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
# Add a gidNumber to all groups
while read DN; do
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	IDNUMBER=$(($FIRST_ID + $RID))
	if [ -t 1 ]; then printf "Adding gidNumber '$IDNUMBER' to '$DN'\n"; fi
 
	TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
	printf "dn: $DN\n" >$TMP_FILE
	printf "changeType: modify\n" >>$TMP_FILE
	printf "add: gidNumber\n" >>$TMP_FILE
	printf "gidNumber: ${IDNUMBER}\n" >>$TMP_FILE
 
	ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
	if [ -t 1 ]; then cat $TMP_FILE; fi
        ((CHANGES++))
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=Group)(!(gidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
if [ $CHANGES -gt 0 ]
then
# Cleanup temp files
	rm /tmp/$(basename $0)-*
# Flush the cache
	net cache flush
else
        if [ -t 1 ]; then printf "No changes made\n"; fi
fi
